leopard/consumer/urls.py
from django.conf.urls import url
from consumer.views import example_view, no_auth_example, basic_auth_example, token_auth_example

urlpatterns = [
    url(r'^no_auth$', no_auth_example, name='no_auth'),
    url(r'^basic_auth$', basic_auth_example, name='basic_auth'),
    url(r'^token_auth$', token_auth_example, name='token_auth'),
    url(r'^$', example_view, name='index'),
]

leopard/leopard/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('consumer.urls', namespace='client')),
]

leopard/consumer/models.py
from django.db import models

# Create your models here.

leopard/consumer/forms.py
from django import forms


class AuthForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

leopard/consumer/views.py
import json
import urllib
import urllib2
from base64 import b64encode
from urlparse import urljoin
from django.shortcuts import render
from django.template import RequestContext
from consumer.forms import AuthForm
from leopard.constants import IGUANA_ADDR


def example_view(request):
    context = RequestContext(request)
    return render(request, 'consumer/index.html', context)


def no_auth_example(request):
    context_data = {}
    url = urljoin(IGUANA_ADDR, 'api/users/?format=json')
    url_request = urllib2.Request(url)
    # request.add_header('key', 'value')
    try:
        response = urllib2.urlopen(url_request)
        value = response.read()
        context_data['output'] = value
    except urllib2.HTTPError as e:
        context_data['output'] = e
    context = RequestContext(request, context_data)

    return render(request, 'consumer/no_auth.html', context)


def basic_auth_example(request):
    context_data = {'form': AuthForm()}
    if request.method == 'POST':
        url = urljoin(IGUANA_ADDR, 'api/users/?format=json')
        url_request = urllib2.Request(url)

        form = AuthForm(request.POST)
        form.is_valid()
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        # Simple Basic Authentication
        pre_encode = username + ":" + password
        encoded_auth = b64encode(pre_encode)
        url_request.add_header('Authorization', 'Basic ' + encoded_auth)
        context_data['info'] = "Added header 'Authorization: Basic %s'" % encoded_auth
        try:
            response = urllib2.urlopen(url_request)
            value = response.read()
            context_data['output'] = value
        except urllib2.HTTPError as e:
            context_data['output'] = e
    else:
        context_data['output'] = "Use the form to request from Iguana using Basic Authentication."

    context = RequestContext(request, context_data)
    return render(request, 'consumer/basic_auth.html', context)


def token_auth_example(request):
    context_data = {'form': AuthForm()}
    if request.method == 'POST':
        url = urljoin(IGUANA_ADDR, 'api/users/?format=json')
        url_request = urllib2.Request(url)

        form = AuthForm(request.POST)
        form.is_valid()
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        # Simple Token Authentication - Step 1, Grab the Token
        token = ""
        token_url = urljoin(IGUANA_ADDR, 'api-token-auth/')
        token_req_data = urllib.urlencode({'username': username, 'password': password})
        token_url_request = urllib2.Request(token_url, token_req_data)
        try:
            response = urllib2.urlopen(token_url_request)
            raw_value = response.read()
            token_dict = json.loads(raw_value)
            context_data['info'] = 'Grabbed token: ' + token_dict.get('token', 'N/A')
            token = token_dict.get('token', 'N/A')
        except urllib2.HTTPError as e:
            context_data['info'] = 'Failed to get token (%s)' % e

        try:
            url_request.add_header('Authorization', 'Token ' + token)
            context_data['info2'] = "Added header 'Authorization: Token %s'" % token
            response = urllib2.urlopen(url_request)
            value = response.read()
            context_data['output'] = value
        except urllib2.HTTPError as e:
            context_data['output'] = e
    else:
        context_data['output'] = "Use the form to request from Iguana using Token Authentication."
    context = RequestContext(request, context_data)
    return render(request, 'consumer/token_auth.html', context)

leopard/consumer/templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : BarbedFlower
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20140322

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Leopard - CMPUT 404 Lab 9</title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link href="http://fonts.googleapis.com/css?family=Varela" rel="stylesheet"/>
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/code.css' %}" rel="stylesheet" type="text/css" media="all"/>
</head>
<body>
<div id="wrapper">
    <div id="header-wrapper">
        <div id="header" class="container">
            <div id="logo">
                <h1><a href="{% url 'client:index' %}">Leopard</a></h1>
            </div>
            <div id="menu">
                <ul>
                    <li><a href="{% url 'client:index' %}" accesskey="1" title="">Homepage</a></li>
                    <li><a href="{% url 'admin:index' %}" accesskey="2" title="">Admin</a></li>
                </ul>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
    <div id="featured">
        <div class="container">
            <img src="{% static 'images/leopard.jpg' %}" alt="Leopard" width="1000"/>
            <div class="title">
                <h2>This is a leopard.</h2>
                <span class="byline">This leopard is fairly majestic.</span>
            </div>
            <p>This is <strong>BarbedFlower</strong>, a free, fully standards-compliant CSS template designed by <a
                    href="http://templated.co" rel="nofollow">TEMPLATED</a>. The photos in this template are from <a
                    href="http://unsplash.com/"> Unsplash</a>. This free template is released under the <a
                    href="http://templated.co/license">Creative Commons Attribution</a> license, so you're pretty much
                free to do whatever you want with it (even use it commercially) provided you give us credit for it. Have
                fun :) </p>
        </div>
        <ul class="actions">
            <li><a href="#" class="button">Etiam posuere</a></li>
        </ul>
    </div>
</div>
<div id="copyright" class="container">
    <p>Photos by <a href="http://unsplash.com/">Unsplash</a> | Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>.
    </p>
</div>
</body>
<!-- Debug Mode, show context -->
<!-- {% filter force_escape %}{% debug %}{% endfilter %} -->
</html>

leopard/consumer/templates/consumer/basic_auth.html
{% extends "base.html" %}
{% block content %}
<div id="extra" class="container">
    <div class="title">
        <h2>Basic Auth Query</h2>
        <span class="byline">Perform a simple 'GET' to the Iguana users API with basic authentication.</span>
    </div>
    <div id="banner" class="content">
        <form id="basic" method="post" action="{% url 'client:basic_auth' %}">
            {% csrf_token %}
            {{ form }}
            <button type="submit" form="basic" value="Submit">Submit</button>
        </form>
        {% if info %}<p>{{ info }}</p>{% endif %}
    </div>
    <div id="content">
    <pre>
            <code>{{ output }}</code>
    </pre>
    </div>
</div>
{% endblock %}

leopard/consumer/templates/consumer/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div id="banner">
    <div class="container">
        <div class="title">
            <h2>Leopard</h2>
            <span class="byline">My cool Leopard app, which can read from that cool Iguana app!</span></div>
    </div>
</div>
<div id="extra" class="container">
    <div class="title">
        <h2>API Queries</h2>
        <span class="byline">Demo the various methods of webapp to webapp authentication</span></div>
    <div id="three-column">
        <div class="boxA">
            <div class="box">
                <p>No Authentication</p>
                <ul class="actions">
                    <li><a href="{% url 'client:no_auth' %}" class="button">No Auth</a></li>
                </ul>
            </div>
        </div>
        <div class="boxB">
            <div class="box">
                <p>HTTP Basic Authentication</p>
                <ul class="actions">
                    <li><a href="{% url 'client:basic_auth' %}" class="button">Basic Auth</a></li>
                </ul>
            </div>
        </div>
        <div class="boxC">
            <div class="box">
                <p>HTTP Token Authentication</p>
                <ul class="actions">
                    <li><a href="{% url 'client:token_auth' %}" class="button">Token Auth</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

leopard/consumer/templates/consumer/no_auth.html
{% extends "base.html" %}
{% block content %}
<div id="extra" class="container">
    <div class="title">
        <h2>No Auth Query</h2>
        <span class="byline">Perform a simple 'GET' to the Iguana users API with no Authentication.</span>
    </div>
    <pre>
        <code>{{ output }}</code>
    </pre>
</div>
{% endblock %}

leopard/consumer/templates/consumer/token_auth.html
{% extends "base.html" %}
{% block content %}
<div id="extra" class="container">
    <div class="title">
        <h2>Token Auth Query</h2>
        <span class="byline">Perform a simple 'GET' to the Iguana users API with token authentication.</span>
    </div>
    <div id="banner" class="content">
        <form id="basic" method="post" action="{% url 'client:token_auth' %}">
            {% csrf_token %}
            {{ form }}
            <button type="submit" form="basic" value="Submit">Submit</button>
        </form>
        <p>
        {% if info %}{{ info }}<br>{% endif %}
        {% if info2 %}{{ info2 }}{% endif %}
        </p>
    </div>
    <div id="content">
    <pre>
            <code>{{ output }}</code>
    </pre>
    </div>
</div>
{% endblock %}